cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-device-motion
cordova plugin add cordova-plugin-device-orientation
cordova plugin add cordova-plugin-dialogs
cordova plugin add cordova-plugin-file
cordova plugin add cordova-plugin-contacts
cordova plugin add cordova-plugin-file-transfer
cordova plugin add cordova-plugin-vibration
cordova plugin add cordova-plugin-globalization
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-media
cordova plugin add cordova-plugin-media-capture
cordova plugin add cordova-plugin-barcodescanner
cordova plugin add cordova-plugin-camera
cordova plugin add https://github.com/phonegap/phonegap-plugin-push --variable SENDER_ID="267214134321"
cordova plugin add cordova-plugin-shake
cordova plugin add cordova-plugin-sms
cordova plugin add cordova-plugin-tts
